# https://github.com/casey/just

# build wasm and js bindings
js:
  rm -rf pkg
  wasm-pack build --target nodejs --out-dir pkg --out-name index
  wasm-pack build --target bundler --out-dir pkg --out-name index_bundle
  cp package.json pkg/package.json
